import { mergeConfig } from 'vitest/config'
import base from './vitest.config'

/** One-shot migration gate (product path + shared infra). */
export default mergeConfig(base, {
  test: {
    pool: 'threads',
    fileParallelism: true,
    exclude: ['**/*.live.spec.ts', '**/*.capture.spec.ts'],
    include: [
      'src/stores/useCamStore.spec.ts',
      'src/stores/useFdmStore.spec.ts',
      'src/stores/useFdmStore.jobsClone.spec.ts',
      'src/stores/useSettingsStore.spec.ts',
      'src/stores/useCarveraStore.spec.ts',
      'src/stores/useGridBotStore.spec.ts',
      'src/stores/useRasterStore.spec.ts',
      'src/stores/useTexturizerStore.spec.ts',
      'src/stores/counter.spec.ts',
      'src/core/cam/**/*.spec.ts',
      'src/core/jobs/**/*.spec.ts',
      'src/core/raster/rasterPathsExportGcode.spec.ts',
      'src/core/gcode/**/*.spec.ts',
      'src/core/bootstrap/**/*.spec.ts',
      'src/core/migration/**/*.spec.ts',
      'src/core/traceKeys.spec.ts',
      'src/core/traceFixtures.spec.ts',
      'src/core/clonePlain.spec.ts',
      'src/core/stableJson.spec.ts',
      'src/core/copyFeedbackMessages.spec.ts',
      'src/core/carvera/**/*.spec.ts',
      'src/core/fdm/**/*.spec.ts',
      'src/core/raster/**/*.spec.ts',
      'src/core/texturizer/**/*.spec.ts',
      'src/core/slicer/**/*.spec.ts',
      'src/core/laser/**/*.spec.ts',
      'src/apps/laser/**/*.spec.ts',
      'src/core/sla/**/*.spec.ts',
      'src/apps/sla/**/*.spec.ts',
      'src/core/mesh/**/*.spec.ts',
      'src/core/utils/download.spec.ts',
      'src/core/devices/**/*.spec.ts',
      'src/composables/useWorkspaceGcodePreview.spec.ts',
      'src/core/gcode/gcodePathBuildCache.spec.ts',
      'src/core/raster/rasterWorkerProtocol.spec.ts',
      'src/composables/useGcodeToolPositionWithMachineFallback.spec.ts',
      'src/composables/useExportActions.spec.ts',
      'src/composables/useFileImportActions.spec.ts',
      'src/components/gcode/**/*.spec.ts',
      'src/api/**/*.spec.ts',
      'src/router/routes.spec.ts',
      'src/types/texturizerWarnings.spec.ts',
    ],
  },
})
