import {
  TRACE_SCHEMA_VERSION,
  TRACE_SCHEMA_VERSION_KEY,
  TRACE_SOURCE_FINGERPRINT_KEY,
  TRACE_SOURCE_LABEL_KEY,
} from './traceKeys'

export const TRACE_FIXTURE_SOURCE_LABEL = 'job-1:Benchy'
export const TRACE_FIXTURE_SOURCE_FINGERPRINT = 'fnv1a32:abcd1234'

export const TRACE_FIXTURE_HEADER_LINES = [
  `${TRACE_SCHEMA_VERSION_KEY}=${TRACE_SCHEMA_VERSION}`,
  `${TRACE_SOURCE_LABEL_KEY}=${TRACE_FIXTURE_SOURCE_LABEL}`,
  `${TRACE_SOURCE_FINGERPRINT_KEY}=${TRACE_FIXTURE_SOURCE_FINGERPRINT}`,
] as const

export const TRACE_FIXTURE_COMMENT_LINES = TRACE_FIXTURE_HEADER_LINES.map((line) => `; ${line}`) as readonly string[]
