import { describe, expect, it } from 'vitest'
import fixture from './fixtures/grip-cam-export-sample.gcode.txt?raw'
import { GRIP_CAM_FIXTURE_MIGRATION_SHA256 } from './camGripFixtureMeta'
import { normalizeCamGcodeForMigrationFingerprint, sha256HexUtf8 } from './camGcodeFingerprint'
import { normalizeCamGcodeText } from './camGcodeNormalize'
import { summarizeCamGcodeMotion } from './camGcodeStats'

describe('camGripFixtureIntegrity', () => {
  it('bundled fixture is non-empty legacy cam_export capture', () => {
    expect(fixture.trim().length).toBeGreaterThan(50)
    expect(fixture).toMatch(/Generated by Kiri:Moto/)
    expect(fixture).toMatch(/G0|G1/)
  })

  it('fixture SHA-256 matches camGripFixtureMeta pin', async () => {
    const fp = normalizeCamGcodeForMigrationFingerprint(fixture)
    expect(await sha256HexUtf8(fp)).toBe(GRIP_CAM_FIXTURE_MIGRATION_SHA256)
  })

  it('fixture contains motion lines for preview stats', () => {
    const m = summarizeCamGcodeMotion(fixture)
    expect(m.nonCommentLines).toBeGreaterThan(0)
    expect(m.g0 + m.g1).toBeGreaterThan(0)
  })
})
