import { describe, expect, it } from 'vitest'
import { normalizeCamGcodeForMigrationFingerprint, sha256HexUtf8 } from './camGcodeFingerprint'

describe('camGcodeFingerprint', () => {
  it('normalizeCamGcodeForMigrationFingerprint trims line ends and outer space', () => {
    expect(normalizeCamGcodeForMigrationFingerprint('G1 X1  \r\nG1 Y2  \r\n')).toBe('G1 X1\nG1 Y2')
  })

  it('drops volatile legacy export timestamp comment lines', () => {
    const text =
      '; Generated by Kiri\n; Mon May 18 2026 00:00:00 GMT+0800 (GMT+08:00)\nG0 X0'
    expect(normalizeCamGcodeForMigrationFingerprint(text)).toBe('; Generated by Kiri\nG0 X0')
  })

  it('sha256HexUtf8 matches known vector for empty string', async () => {
    const out = await sha256HexUtf8('')
    expect(out).toBe('e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855')
  })
})
