import { describe, expect, it } from 'vitest'
import { normalizeCamGcodeForMigrationFingerprint, sha256HexUtf8 } from './camGcodeFingerprint'
import { normalizeCamGcodeText } from './camGcodeNormalize'
import fixture from './fixtures/grip-cam-export-sample.gcode.txt?raw'
import { GRIP_CAM_FIXTURE_MIGRATION_SHA256 } from './camGripFixtureMeta'
describe('camGripFixtureNormalize', () => {
  it('normalizes bundled legacy cam_export capture', () => {
    const out = normalizeCamGcodeText(fixture)
    expect(out.length).toBeGreaterThan(100)
    expect(out).toContain('G21')
    expect(out).toContain('Generated by Kiri:Moto')
    expect(out).not.toMatch(/\r/)
  })

  it('normalizes CRLF as in grip cam_export flush batches', () => {
    expect(normalizeCamGcodeText('G20\r\nG90\r\nM5\r\n')).toBe('G20\nG90\nM5')
  })

  it('fixture migration SHA-256 is pinned (grip parity / session bundle hints)', async () => {
    const fp = normalizeCamGcodeForMigrationFingerprint(fixture)
    expect(await sha256HexUtf8(fp)).toBe(GRIP_CAM_FIXTURE_MIGRATION_SHA256)
  })
})
