export type RiskLevel = 'high' | 'medium' | 'low'

export function getRiskLevelForKey(key: string): RiskLevel {
  if (key === 'deviceName' || key === 'ops') return 'high'
  if (key === 'camCustomGcode') return 'high'
  if (key === 'camZBottom' || key === 'camZClearance' || key === 'camZAnchor') return 'high'
  if (key === 'camStockOn') return 'high'
  if (key === 'camZThru') return 'high'
  if (key === 'camStockX' || key === 'camStockY' || key === 'camStockZ') return 'medium'
  if (key === 'camOriginTop') return 'medium'
  if (key === 'camOriginCenter') return 'medium'
  if (key === 'camStockOffset' || key === 'camStockClipTo') return 'medium'
  if (key === 'camStockIndexed' || key === 'camStockIndexGrid') return 'medium'
  if (key === 'camDepthFirst') return 'medium'
  if (key === 'camInnerFirst') return 'medium'
  if (key === 'camToolInit') return 'medium'
  if (key === 'camForceZMax') return 'medium'
  if (key === 'camFullEngage') return 'medium'
  if (key === 'camFlatness') return 'medium'
  if (key === 'camTrueShadow') return 'medium'
  if (key.startsWith('camOriginOff')) return 'medium'
  if (key === 'camExpertFast') return 'low'
  if (key === 'camArcEnabled') return 'low'
  if (key === 'camFirstZMax') return 'medium'
  if (key === 'ctOriginCenter' || key === 'ctOriginBounds') return 'medium'
  if (key.startsWith('ctOriginOff')) return 'medium'
  if (key === 'outputInvertX' || key === 'outputInvertY') return 'medium'
  if (key === 'camArcTolerance' || key === 'camArcResolution') return 'medium'
  if (key === 'camTolerance' || key === 'camConventional') return 'medium'
  if (key.startsWith('camLaser')) return 'medium'
  if (key.startsWith('camLathe')) return 'medium'
  if (key.startsWith('camHelical')) return 'medium'
  if (key.startsWith('camRegister')) return 'medium'
  if (key.startsWith('camLevel')) return 'medium'
  if (key.startsWith('camFlip')) return 'medium'
  if (key.startsWith('camIndex')) return 'medium'
  if (key.startsWith('camTabs')) return 'medium'
  if (key.startsWith('camEase')) return 'medium'
  if (key.startsWith('camPocket')) return 'medium'
  if (key.startsWith('camRough')) return 'medium'
  if (key.startsWith('camOutline')) return 'medium'
  if (key.startsWith('camTrace')) return 'medium'
  if (key.startsWith('camContour')) return 'medium'
  if (key.startsWith('camDrill')) return 'medium'
  if (key.startsWith('camZ')) return 'medium'
  if (key.startsWith('camFastFeed')) return 'medium'
  return 'low'
}
