import type { SlicePath2D, SlicePreviewData, SliceResult } from '@/api/slice'
import type { FdmProcess } from '@/types/process'

export type FdmGcodeSource =
  | 'legacy-preview-path'
  | 'placeholder-empty'
  | 'legacy-fdm-export'

export interface BuildFdmGcodeFromPreviewOptions {
  process: FdmProcess
  deviceName?: string
  jobName?: string
  /** Nozzle diameter mm (default 0.4). */
  nozzleMm?: number
  /** Filament diameter mm (default 1.75). */
  filamentMm?: number
  /** Soft cap on motion segments (safety). */
  maxSegments?: number
  headerLines?: string[]
}

export interface FdmGcodeFromPreviewResult {
  gcodeText: string
  source: FdmGcodeSource
  segmentCount: number
  extrudedMm: number
}

/** grip FDM `extrudePerMM(noz, fil, slice)` */
export function extrudePerMm(nozzleMm: number, filamentMm: number, sliceHeightMm: number): number {
  const noz = Math.max(1e-6, nozzleMm)
  const fil = Math.max(1e-6, filamentMm)
  const slice = Math.max(1e-6, sliceHeightMm)
  return ((Math.PI * (noz / 2) ** 2) / (Math.PI * (fil / 2) ** 2)) * (slice / noz)
}

function dist2(a: [number, number], b: [number, number]): number {
  const dx = b[0] - a[0]
  const dy = b[1] - a[1]
  return Math.hypot(dx, dy)
}

function feedMmMin(mmPerSec: number | undefined, fallback: number): number {
  const v = Number(mmPerSec)
  if (!Number.isFinite(v) || v <= 0) return fallback
  return Math.round(v * 60)
}

function isExtrudingPath(path: SlicePath2D): boolean {
  return path.type === 'perimeter' || path.type === 'infill' || path.type === 'support'
}

/**
 * Build machine-oriented G-code from slice preview paths (legacy `fdm_slice` layers).
 * Not a full `fdm_prepare`/`fdm_export` substitute — bridges printable output until those land.
 */
export function buildFdmGcodeFromPreview(
  preview: SlicePreviewData | undefined | null,
  opts: BuildFdmGcodeFromPreviewOptions,
): FdmGcodeFromPreviewResult {
  const process = opts.process
  const nozzleMm = opts.nozzleMm ?? process.sliceLineWidth ?? 0.4
  const filamentMm = opts.filamentMm ?? 1.75
  const layerH = process.sliceHeight || 0.2
  const ePerMm = extrudePerMm(nozzleMm, filamentMm, layerH)
  const maxSegments = Math.max(100, opts.maxSegments ?? 250_000)

  const printF = feedMmMin(process.outputFeedrate, 3600)
  const seekF = feedMmMin(process.outputSeekrate, 7200)
  const firstF = feedMmMin(process.firstLayerRate, 1200)
  const nozzleTemp = process.firstLayerNozzleTemp || process.outputTemp || 200
  const bedTemp = process.firstLayerBedTemp || process.outputBedTemp || 60
  const retractDist = Math.max(0, Number(process.outputRetractDist) || 0)
  const retractSpeed = feedMmMin(process.outputRetractSpeed, 2400)
  const fanSpeed = Math.max(0, Math.min(255, Math.round(((process.outputFanSpeed ?? 0) / 100) * 255)))
  const fanLayer = Math.max(0, Math.floor(process.outputFanLayer ?? 0))

  const lines: string[] = [
    '; FDM bridge G-code generated by shape_cam',
    '; gcodeSource=legacy-preview-path',
    '; note=path export from fdm_slice preview (fallback when fdm_prepare/export unavailable)',
  ]
  if (opts.jobName) lines.push(`; job=${opts.jobName}`)
  if (opts.deviceName) lines.push(`; device=${opts.deviceName}`)
  lines.push(`; process=${process.processName || 'default'}`)
  if (opts.headerLines?.length) lines.push(...opts.headerLines)

  lines.push('G21 ; mm')
  lines.push('G90 ; absolute XYZ')
  lines.push('M82 ; absolute E')
  lines.push(`M104 S${Math.round(nozzleTemp)} ; hotend`)
  lines.push(`M140 S${Math.round(bedTemp)} ; bed`)
  lines.push(`M109 S${Math.round(nozzleTemp)}`)
  lines.push(`M190 S${Math.round(bedTemp)}`)
  lines.push('G92 E0')
  lines.push('')

  const layers = preview?.layers ?? []
  if (!layers.length) {
    lines.push('; placeholderPath=1 (no preview layers)')
    lines.push('G0 X0 Y0')
    lines.push('M104 S0')
    lines.push('M140 S0')
    lines.push('M84')
    lines.push('')
    return {
      gcodeText: lines.join('\n'),
      source: 'placeholder-empty',
      segmentCount: 0,
      extrudedMm: 0,
    }
  }

  let eAbs = 0
  let segments = 0
  let last: { x: number; y: number; z: number } | null = null
  let fanOn = false

  for (let li = 0; li < layers.length; li += 1) {
    if (segments >= maxSegments) {
      lines.push(`; truncated at maxSegments=${maxSegments}`)
      break
    }
    const layer = layers[li]!
    const z = Number.isFinite(layer.z) ? layer.z : li * layerH
    const fPrint = li === 0 ? firstF : printF
    lines.push(`;LAYER:${li} z=${z.toFixed(4)}`)

    if (!fanOn && fanSpeed > 0 && li >= fanLayer) {
      lines.push(`M106 S${fanSpeed}`)
      fanOn = true
    }

    for (const path of layer.paths) {
      const pts = path.points
      if (!pts?.length) continue
      const extrude = isExtrudingPath(path)
      const p0 = pts[0]!
      const x0 = p0[0] ?? 0
      const y0 = p0[1] ?? 0
      if (!Number.isFinite(x0) || !Number.isFinite(y0)) continue

      if (last && retractDist > 0 && extrude) {
        eAbs = Math.max(0, eAbs - retractDist)
        lines.push(`G1 E${eAbs.toFixed(5)} F${retractSpeed}`)
      }

      lines.push(`G0 X${x0.toFixed(4)} Y${y0.toFixed(4)} Z${z.toFixed(4)} F${seekF}`)
      segments += 1
      last = { x: x0, y: y0, z }

      if (retractDist > 0 && extrude) {
        eAbs += retractDist
        lines.push(`G1 E${eAbs.toFixed(5)} F${retractSpeed}`)
      }

      for (let i = 1; i < pts.length; i += 1) {
        if (segments >= maxSegments) break
        const p = pts[i]!
        const x = p[0] ?? 0
        const y = p[1] ?? 0
        if (!Number.isFinite(x) || !Number.isFinite(y)) continue
        const d = dist2([last!.x, last!.y], [x, y])
        if (d < 1e-6) continue
        if (extrude) {
          eAbs += d * ePerMm
          lines.push(`G1 X${x.toFixed(4)} Y${y.toFixed(4)} E${eAbs.toFixed(5)} F${fPrint}`)
        } else {
          lines.push(`G0 X${x.toFixed(4)} Y${y.toFixed(4)} F${seekF}`)
        }
        last = { x, y, z }
        segments += 1
      }
    }
  }

  lines.push('')
  lines.push(`; extrudedMm=${eAbs.toFixed(2)} segments=${segments}`)
  lines.push('M104 S0')
  lines.push('M140 S0')
  lines.push('M106 S0')
  lines.push('M84')
  lines.push('')

  return {
    gcodeText: lines.join('\n'),
    source: 'legacy-preview-path',
    segmentCount: segments,
    extrudedMm: eAbs,
  }
}

export function buildFdmGcodeFromSliceResult(
  result: SliceResult,
  opts: BuildFdmGcodeFromPreviewOptions,
): FdmGcodeFromPreviewResult {
  return buildFdmGcodeFromPreview(result.preview, opts)
}
